name: vibedterm
packages:
  - packages/**
  - apps/**

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze: melos exec -- flutter analyze
  test: melos exec -- flutter test
  format: melos exec -- flutter format .
  check: |
    melos analyze
    melos exec --scope="core_vault" -- flutter test
    melos exec --scope="core_ssh" -- flutter test
    melos exec --scope="ssh_client_app" -- flutter test
